### ISSUE TITLE
border

### ISSUE THREAD

**Issue by Kazturin** [1904labs/dom-to-image-more#154]
Hello.
Each element has a border as a result.

**Comment by Josh961** [comment]
Had to pull down the code and fix this one for what I'm doing. After a little bit of playing around, the problem method was `copyOptions()` under `toSvg()` on line 91 in dom-to-image-more.js.

I just ended up copy pasting dom-to-image-more.js into my project, deleted that line and method, and the border issue was solved. This was enough for my use case. I didn't need to use copyDefaultStyles, imagePlaceholder, cacheBust, etc.

**Comment by IDisposable** [comment]
What was the specific change you needed, would be happy to integrate.

**Comment by Josh961** [comment]
Just to give some context to what the issue looked like, for whatever reason, I was getting gray borders around each div in my generated images (ignore watermarks):

![image](https://github.com/1904labs/dom-to-image-more/assets/14829786/3e24fd16-f73b-46f7-a223-3356f1606495)

Deleting `copyOptions()` gave me correct images:

![image](https://github.com/1904labs/dom-to-image-more/assets/14829786/f4c89bf7-1a15-47a2-89a4-33274d5a7a72)

I'm not sure why this fixes things. I did not dive that deep into it. Only deduced what method was causing the issue and deleted it without problems.

In reference to the specific change, I guess you could integrate an optional parameter to skip applying options?

**Comment by rr210** [comment]
> Just to give some context to what the issue looked like, for whatever reason, I was getting gray borders around each div in my generated images (ignore watermarks):只是为了提供一些背景信息来说明问题的情况，无论出于何种原因，我在生成的图像中的每个 div 周围都出现了灰色边框（忽略水印）：
> 
> ![image](https://private-user-images.githubusercontent.com/14829786/301697197-3e24fd16-f73b-46f7-a223-3356f1606495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTY4OTcsIm5iZiI6MTcxMzg1NjU5NywicGF0aCI6Ii8xNDgyOTc4Ni8zMDE2OTcxOTctM2UyNGZkMTYtZjczYi00NmY3LWEyMjMtMzM1NmYxNjA2NDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNTM2ZjhiNzdjZDE1YzY4MGY3YTRkNTU4MTE5NmZjMzEzNGJjZjk0YWRkZmFhNTEwN2Q4MGQ0MjQwZWU1NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6_NhRFz7TIbg8394X6PZ4rOC1IWTUZtY9uf0lXbQJw)
> 
> Deleting `copyOptions()` gave me correct images:删除 `copyOptions()` 给了我正确的图像：
> 
> ![image](https://private-user-images.githubusercontent.com/14829786/301697510-f4c89bf7-1a15-47a2-89a4-33274d5a7a72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTY4OTcsIm5iZiI6MTcxMzg1NjU5NywicGF0aCI6Ii8xNDgyOTc4Ni8zMDE2OTc1MTAtZjRjODliZjctMWExNS00N2EyLTg5YTQtMzMyNzRkNWE3YTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMTRlYWRhOGIzOWYxYzExNmFjZmE5MzA0OWU1MmIwOGExZTk5YzAxY2M5ZjI5NjZmNzRiMDdiOTM4YTlhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vSD94Kjy-lhmG5Oy3QYFbduKF64XqczU5u9_iq44Zbw)
> 
> I'm not sure why this fixes things. I did not dive that deep into it. Only deduced what method was causing the issue and deleted it without problems.我不知道为什么这可以解决问题。我并没有深入研究它。仅推断出导致问题的方法并将其删除，没有出现任何问题。
> 
> In reference to the specific change, I guess you could integrate an optional parameter to skip applying options?关于具体的更改，我想您可以集成一个可选参数来跳过应用选项？

I deleted it but the problem is not solved, there is still a border.
<img width="437" alt="image" src="https://github.com/1904labs/dom-to-image-more/assets/66169324/c64d4291-0854-479c-a6b7-132774ab3161">

**Comment by risalfajar** [comment]
Is there no solution yet? This is critical

**Comment by IDisposable** [comment]
I still need a minimal repro as a JSFiddle, please

**Comment by PhamMinhKha** [comment]
same

**Comment by srsholmes** [comment]
Use [html-to-image](https://www.npmjs.com/package/html-to-image) as an alternative.

**Comment by jaykilleen** [comment]
+1 on this issue. Struggling to find a fix for this locally. For context. `dom-to-image` library was working well (but would sometimes silently fail) and after switching to this new library I am getting the gray borders.

I tried the `html-to-image` `toBlob` along with `FileSaver` and it has resolved the problem.

**Comment by alaynatruttmann** [comment]
In the options, I set `copyDefaultStyles: false` and that seems to have fixed the border issue for me without any adverse effects on my images.

**Comment by matthewvogas** [comment]
> In the options, I set `copyDefaultStyles: false` and that seems to have fixed the border issue for me without any adverse effects on my images.

Yes, into

```
  const generateImage = useCallback((options = {}, download = false) => {
    if (ref.current) {
      return domtoimage
        .toJpeg(ref.current, { copyDefaultStyles: false }) <-- use this
        .then((dataUrl) => {
```
